# Generated by Django 5.2 on 2025-04-12 10:08

import django.db.models.deletion
>>>>>>> roman
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('has_ramp', models.BooleanField(default=False)),
                ('has_tactile_elements', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('accessible_toilet', models.BooleanField(default=False)),
                ('easy_entrance', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='inclusive_map.place')),
            ],
        ),
    ]
