# Generated by Django 5.2 on 2025-04-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('has_ramp', models.BooleanField(default=False)),
                ('has_tactile_elements', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('accessible_toilet', models.BooleanField(default=False)),
                ('easy_entrance', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='places/')),
            ],
        ),
    ]
