# Generated by Django 5.2 on 2025-04-12 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_map', '0003_accessibilitysuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessibilitysuggestion',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AddField(
            model_name='accessibilitysuggestion',
            name='status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Схвалено'), ('rejected', 'Відхилено')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='accessibilitysuggestion',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
