# Generated by Django 5.2 on 2025-04-12 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inclusive_map', '0005_accessibilitysuggestion_submitted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessibilitysuggestion',
            name='submitted_by',
        ),
    ]
