# Generated by Django 5.2 on 2025-04-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_special_needs',
            field=models.BooleanField(default=False),
        ),
    ]
